<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="KioskApp.Core\Interfaces\" />
    <Folder Include="KioskApp.Core\Services\" />
    <Folder Include="KioskApp.Models\" />
    <Folder Include="KioskApp.Services\Api\" />
    <Folder Include="KioskApp.Services\HardwareMock\" />
    <Folder Include="KioskApp.Services\DTOs\" />
    <Folder Include="KioskApp.Shared\" />
    <Folder Include="KioskApp.UI\Assets\" />
    <Folder Include="KioskApp.UI\Controls\" />
    <Folder Include="KioskApp.UI\ViewModels\" />
  </ItemGroup>

</Project>
